hash_funcs_names: ["poly", "cr32", "cr32_intrinsic", "fchar", "fnv"]

versions:
  - name : v1 # версия без оптимизаций
    compile_flags : "-O0 -march=native -D NDEBUG"
    launch_flags : "--hash=cr32"

  - name : v2 # версия с компиляторными оптимизациями
    compile_flags : "-O3 -march=native -mtune=native -D NDEBUG "
    launch_flags : "--hash=cr32"

  - name : v3 # версия с intrinsic оптимизацией функции cr32
    compile_flags : "-O3 -march=native -mtune=native -D NDEBUG"
    launch_flags : "--hash=cr32_intrinsic"

  - name : v4 # версия с использованием собственной реализацией функции streq на ассемблере
    compile_flags : "-O3 -march=native -mtune=native -D MY_STREQ -D NDEBUG "
    launch_flags : "--hash=cr32_intrinsic"

  - name : v5 # версия с использованием inline функции streq с ассемблерными вставками
    compile_flags : "-O3 -march=native -mtune=native -masm=intel -D INLINE_ASM_STREQ -D NDEBUG "
    launch_flags : "--hash=cr32_intrinsic"

  - name : v6 # версия с использованием inline хэш-функции cr32 на intrinsic
    compile_flags : "-O3 -march=native -mtune=native -masm=intel -D INLINE_ASM_STREQ -D INLINE_INTINSIC_CR32 -D NDEBUG"
    launch_flags : "--hash=cr32_intrinsic"

tests_gen:
    data_dir : data

    text_path : ./war_and_peace.txt
    tests_outpath :
    text_outpath : ./tests.txt


    text_words_cnt : 40000
    tests_cnt : 40000
    tests_outfile : tests.txt
    text_outfile : text.txt

data_folder:
    name : data



perf_flags : -g -T --running-time --call-graph dwarf -F 20000

results:
    dir : results
    load_factor_file : load_factor
    vers_benchmarks_res : versions_benchmarks
    hash_funcs_res_dir:
      name : hash_funcs
      data_dir : data
      img_dir : img
    hash_data_dir_path : hash_funcs/data
    versions_executables_dir : execs
    versions_profiling_dir : profiling



launch_modes:
  versions_benchmarks:
    heat_cnt : 10 # количество холостых операций find_key для прогрева перед основным измерением
    selected_versions: # "vi" : <benchmark runs cnt>
      v1 : 100
      v2 : 100
      v3 : 100
      v4 : 100
      v5 : 100
      v6 : 100

  versions_build:
    selected_versions: ["v1", "v2", "v3", "v4", "v5", "v6"]
  hashes_benchmarks:
    compile_flags: -O3 -march=native -mtune=native


makefike:
  build_dir: build



# python3 run.py gen_tests
# python3 run.py versions_benchmarks
# python3 run.py hashes_benchmarks
# python3 run.py load_factor_benchmark
# python3 run.py build_all_versions
# python3 run.py versions_profiling